#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
/*Robotc will go to the first base*/
task main()
{
forward(2.0, rotations, 50);
turnLeft(120, degrees);
forward(5.1, rotations,50);
turnLeft(229, degrees);
forward(4.4, rotations, 50);
turnLeft(180, degrees);
forward(2.4,rotations,50);
turnRight(350, degrees);
//*Robotc has reacht the first check point*//
forward(3.5, rotations, 50);
turnRight(180, degrees);
forward(5.7, rotations, 50);
turnRight(180, degrees, 50);
forward(5.0, rotations, 50);
}
/*Robotc reach the end*/
