#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int encoderLine1;
//*This program will make the robot go backwards to the black line and keep the encoder counts*//
task main()
{
turnLeft(360, degrees,50);
resetMotorEncoder(leftMotor);

setMotorSpeed(leftMotor, -30);
setMotorSpeed(rightMotor, -30);
//*This part it is driving backwards to the blackline*//
waitUntil(getColorName(colorSensor) == colorBlack);

setMotorSpeed(leftMotor, -30);
setMotorSpeed(rightMotor, -30);

encoderLine1 = getMotorEncoder(leftMotor);
//It has reach the black line*//
}
