#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int encoderLine1;
int encoderLine2;
void forwardOneLine()
{
setMotorSpeed(leftMotor,30);
setMotorSpeed(rightMotor,30);

waitUntil(getColorName(colorSensor) !=colorBlack);

setMotorSpeed(leftMotor,0);
setMotorSpeed(rightMotor,0);

sleep(3000);

setMotorSpeed(leftMotor,30);
setMotorSpeed(rightMotor,30);

waitUntil(getColorName(colorSensor) ==colorBlack);

setMotorSpeed(leftMotor,0);
setMotorSpeed(rightMotor,0);


}
task main()
{
	resetMotorEncoder(leftMotor);
	forwardOneLine();
	encoderLine1 = getMotorEncoder(leftMotor);
	forwardOneLine();
	encoderLine2 = getMotorEncoder(leftMotor);
}
