#pragma config(StandardModel, "EV3_REMBOT")

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//



int encoderLine1;
int encoderLine2;
int encoderLine3;

float distanceLine1;
float distanceLine2;
float distanceLine3;

//*In this program i made the robot go to lines and turn around as well as convert encoder in centimeter*//
void forwardOneLine()
{
resetMotorEncoder(leftMotor);
  setMotor(motorB, 30);
  setMotor(motorC, 30);
   waitUntil(getColorName(colorSensor) == colorBlack);
  stopAllMotors();
}
  float convertEncorderToCM(int encorderCounts)
{
    return (encorderCounts / 360.0)*(PI*5.6);
}

task main()
{
resetMotorEncoder(leftMotor);
forwardOneLine();
encoderLine1 = getMotorEncoder(leftMotor);
turnLeft(360,degrees,50);
resetMotorEncoder(leftMotor);
forwardOneLine();
encoderLine1 = getMotorEncoder(leftMotor);
turnLeft(360,degrees,50);
resetMotorEncoder(leftMotor);
sleep(10000);

displayTextLine(1,"line1: %f cm", distanceLine1);
displayTextLine(2,"line2: %f cm", distanceLine2);
//*Here we display the cm counted in the dubugger window.*//
displayTextLine(3,"line3: %f cm", distanceLine3);

distanceLine1 = convertEncorderToCM(distanceLine1);
distanceLine2 = convertEncorderToCM(distanceLine2);
distanceLine3 = convertEncorderToCM(distanceLine3);

displayTextLine(1,"line1: %f cm", distanceLine1);
displayTextLine(2,"line2: %f cm", distanceLine2);
displayTextLine(3,"line3: %f cm", distanceLine3);
}
