#pragma config(StandardModel, "RVW Anemobot")
#pragma config(RenamedStdModelMotor, motorA, armMotor)
#pragma config(RenamedStdModelSensor, S3, colorSensor)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//* In this program I will make the robot go inside the pipeline and detects the pipes and calculate it into centimeters and bring the result back on the remote screen*//
int encoderLine1;
int encoderLine2;
int encoderLine3;

float distanceLine1;
float distanceLine2;
float distanceLine3;

//* I make functions so that it will be easier to write and understand*//
void forwardOneLine()
{
    setMultipleMotors(50, motorB, motorC);
    waitUntil(getColorName(colorSensor) == colorBlack);
}
void crossTheLine()
{
    setMultipleMotors(40, motorB, motorC);
    waitUntil(getColorName(colorSensor)!= colorBlack);
}

void DontCrossTheLine()
{
    setMultipleMotors(-40, motorB, motorC);
    waitUntil(getColorName(colorSensor)!= colorBlack);
}

void backTheLine()
{
	 setMultipleMotors(-40, motorB, motorC);
    waitUntil(getColorName(colorSensor)!= colorBlack);
}

void DontCrossTheLine()
{
    setMultipleMotors(-40, motorB, motorC);
    waitUntil(getColorName(colorSensor)!= colorBlack);
}

void backwardOneLine()
{
		 setMultipleMotors(-50, motorB, motorC);
    waitUntil(getColorName(colorSensor) == colorBlack);
}

float convertEncoderToCM(int encoderCounts)
{
  return (encoderCounts / 360.0)*(PI*5.6);
}
task main()
{
resetMotorEncoder(leftMotor);
forwardOneLine();
crossTheLine();
encoderLine1 = getMotorEncoder(motorB);
forwardOneLine();
crossTheLine();
encoderLine2 = getMotorEncoder(motorB);
setMultipleMotors(50, motorB, motorC);
waitUntil(getUSDistance(sonarSensor)< 15);
setMultipleMotors(-50, motorB, motorC);
encoderLine3 = getMotorEncoder(motorB);
waitUntil(getMotorEncoder(motorB) < 0);
//* Here it will convert into CM and also display the results*//
distanceLine1 = convertEncoderToCM(encoderLine1);
distanceLine2 = convertEncoderToCM(encoderLine2);
distanceLine3 = convertEncoderToCM(encoderLine3);

displayTextLine(1,"Pipe1: %f cm", distanceLine1);
displayTextLine(2,"Pipe2: %f cm", distanceLine2);
//*This part it displays  the counts.*//
displayTextLine(3,"Pipe3: %f cm", distanceLine3);
}
