#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//*This program will use the codelibrary to instead put function*//
#include "CodeLibrary_tuey_701.h"
int encoderLine1;
//*It will begin here*//
task main()
{
	repeat(2)
{
		resetMotorEncoder(leftMotor);
		forward_one_line();
		encoderLine1 = getMotorEncoder(leftMotor);
}
}
//*Here it will follows the same steps.*//
