#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//*In this challeng I made the robot make different functions and to do on each color pattern floor so it won't be too confusing.*//
void green()
{
setMultipleMotors(50,motorB,motorC);
waitUntil(getColorName(colorSensor) ==colorGreen);
turnLeft(360,degrees,50);
}
//*This is an example of a command that is made for blue pattern*//
void blue()
{
setMotorSpeed(motorB, -50);
setMotorSpeed(motorC, -50);
waitUntil(getColorName(colorSensor) ==colorBlue);
setMotorSpeed(motorB, 0);
setMotorSpeed(motorC, 0);
}
void blue2()
{
	turnLeft(279, degrees, 20);
	turnLeft(90,degrees,50);
	setMotorSpeed(motorB, -50);
  setMotorSpeed(motorC, -50);
  waitUntil(getColorName(colorSensor) ==colorRed);
  setMotorSpeed(motorB, 0);
  setMotorSpeed(motorC, 0);
}
task main()
{
//*It will repeat the same loop again 3 more times*//
	repeat(3)
{
	green();
	blue();
	blue2();
	stopAllMotors();
}
	}
