#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//*In thia code I will make the robot find the area as  well as display it.//*
int encoderLine1;
int encoderLine2;
int encoderLine3;
int encoderLine4;

float distanceLine1;
float distanceLine2;
float distanceLine3;
float distanceLine4;

void forwardOneLine()
{
	setMultipleMotors(50, motorB, motorC);
	waitUntil(getColorName(colorSensor) == colorBlack);
}
void crossTheLine()
{
	setMultipleMotors(40, motorB, motorC);
	waitUntil(getColorName(colorSensor)!= colorBlack);
}

float convertEncoderToCM(int encoderCounts)
{
  return (encoderCounts / 360.0)*(PI*5.6);
}
//* i made function converttocm so that it use the coutns to cm and also display it at the end.*//
task main()
{
resetMotorEncoder(leftMotor);
crossTheLine();
forwardOneLine();
encoderLine1 = getMotorEncoder(motorB);
turnLeft(180,degrees,50);
resetMotorEncoder(leftMotor);
crossTheLine();
forwardOneLine();
encoderLine2 = getMotorEncoder(motorB);
turnLeft(190,degrees,50);
resetMotorEncoder(leftMotor);
crossTheLine();
forwardOneLine();
turnLeft(180,degrees,50);
resetMotorEncoder(leftMotor);
crossTheLine();
forwardOneLine();
encoderLine3 = getMotorEncoder(motorB);



distanceLine1 = convertEncoderToCM(encoderLine1);
distanceLine2 = convertEncoderToCM(encoderLine2);
distanceLine3 = convertEncoderToCM(encoderLine3);

displayTextLine(1,"line1: %f cm", distanceLine1);
displayTextLine(2,"line2: %f cm", distanceLine2);
//*This part it displays  the counts.*//
displayTextLine(3,"line3: %f cm", distanceLine3);
}
