#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
forward(1,rotations,50);
turnLeft(180,degrees,50);
forward(3,rotations,50);
turnRight(180,degrees,50);
forward(3,rotations,50);
turnLeft(155,degrees,50);
forward(4,rotations,50);
}
