#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//*DISCLAIMER: BEFORE YOU RUN THE ROBOT MAKE SURE THE ROOMS ARE THE SAME ACCODING TO THE VIDEO*//
task main()
{
	if(getUSDistance(sonarSensor) > 135)
	setMotorSpeed(motorB, 50);
	setMotorSpeed(motorC, 50);
	waitUntil(getColorName(colorSensor) ==colorYellow);
	setMotorSpeed(motorB, 0);
	setMotorSpeed(motorC, 0);
	wait(6,seconds);
	forward(1,rotations,50);
	turnLeft(165,degrees,50);
	setMotorSpeed(motorB, 50);
	setMotorSpeed(motorC, 50);
	waitUntil(getUSDistance(sonarSensor) < 30);
	setMotorSpeed(motorB, 0);
	setMotorSpeed(motorC, 0);
	turnLeft(180,degrees,50);
	forward(3,rotations,50);
	turnRight(180,degrees,50);
	forward(4,rotations,50);
	turnLeft(183,degrees,50);
	moveMotor(armMotor, -54, degrees, 30);
forward(6.3, rotations, 100);
moveMotor(armMotor, 84, degrees, 30);
forward(1,rotations,50);
turnLeft(180,degrees,50);
forward(9,rotations,50);
turnLeft(165,degrees,50);
forward(2.5,rotations,50);
setLEDColor(ledOrange);
}
