#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
forward(4,rotations,50);
turnLeft(165,degrees,50);
forward(2.5,rotations,50);
setLEDColor(ledOrange);
}
