#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
moveMotor(armMotor, -54, degrees, 30);
forward(2.6, rotations, 100);
moveMotor(armMotor, 84, degrees, 30);
}
