#pragma config(StandardModel, "RVW Mammalbot")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
turnLeft(1,rotations,50);
turnLeft(50,degrees,50);
forward(2.5,rotations,50);
turnLeft(30,degrees,50);
setMotor(mammalAttachment, 40);
wait(1, seconds);
stopMotor(mammalAttachment);
turnRight(80,degrees,50);
forward(3,rotations,50);
turnRight(150,degrees,50);
forward(4.5,rotations,50);
turnLeft(100,degrees,50);
forward(2,rotations,50);
setMotor(mammalAttachment, -40);
wait(1, seconds);
stopMotor(mammalAttachment);
}
