#pragma config(StandardModel, "RVW Mammalbot")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
turnRight(90,degrees,50);
forward(1.5,rotations,50);
setMotor(mammalAttachment, 40);
wait(1, seconds);
stopMotor(mammalAttachment);
backward(2,rotations,50);
turnLeft(1,rotations,50);
forward(3,rotations,50);
turnRight(90,degrees,50);
forward(6,rotations,50);
turnRight(55,degrees,50);
forward(7,rotations,50);
setMotor(mammalAttachment, -40);
wait(1, seconds);
stopMotor(mammalAttachment);
}
