#pragma config(StandardModel, "RVW Mammalbot")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
forward(5,rotations,50);
turnRight(100,degrees,50);
forward(1,rotations,50);
setMotor(mammalAttachment, 40);
wait(1, seconds);
stopMotor(mammalAttachment);
backward(2,rotations,50);
turnRight(200,degrees,50);
forward(12,rotations,50);
setMotor(mammalAttachment, -40);
wait(1, seconds);
stopMotor(mammalAttachment);
}
