#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
repeat(100000000000000000000000);
 if(getGyroDegrees(gyroSensor)<0)
        {
            setMotor(motorB,30);
            setMotor(motorC,0);

      	}
    else
        {
        setMotor(motorB,0);
        setMotor(motorC,30);

     }
}
