

#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int encoderLine1;
int encoderLine2;
int encoderLine3;

float distanceLine1;
float distanceLine2;
float distanceLine3;

void forwardOneLine()
{
    setMultipleMotors(50, motorB, motorC);
    waitUntil(getColorName(colorSensor) == colorBlack);
}

void crossTheLine()
{
    setMultipleMotors(40, motorB, motorC);
    waitUntil(getColorName(colorSensor)!= colorBlack);
}

float convertEncoderToCM(int encoderCounts)
{
  return (encoderCounts / 360.0)*(PI*5.6);
}

task main()
{
forwardOneLine();
encoderLine1 = getMotorEncoder(leftMotor);
turnRight(360,degrees,50);
resetMotorEncoder(leftMotor);
setMotorSpeed(leftMotor, 30);
setMotorSpeed(rightMotor, 30);
waitUntil(getMotorEncoder(leftMotor) > encoderLine1);
turnRight(365,degrees,30);
resetMotorEncoder(leftMotor);
encoderLine2 = encoderLine1 * 2.4;
setMotorSpeed(leftMotor, 30);
setMotorSpeed(rightMotor, 30);
waitUntil(getMotorEncoder(leftMotor) > encoderLine2);
waitUntil(getMotorEncoder(leftMotor) > encoderLine2);
turnRight(360,degrees,50);
//*This will make the encoder multiply 2 and 3 times from the firrst encoderline*//
resetMotorEncoder(leftMotor);
setMotorSpeed(leftMotor, 30);
setMotorSpeed(rightMotor, 30);
waitUntil(getMotorEncoder(leftMotor) > encoderLine2);
turnRight(365,degrees,30);
resetMotorEncoder(leftMotor);
encoderLine3 = encoderLine1 * 3.6;
setMotorSpeed(leftMotor, 30);
setMotorSpeed(rightMotor, 30);
waitUntil(getMotorEncoder(leftMotor) > encoderLine3);
waitUntil(getMotorEncoder(leftMotor) > encoderLine3);
turnRight(360,degrees,50);
forward(2,rotations,50);

forward(5.2,rotations,50);
//* This is the end and the robot has finished turning around*//
distanceLine1 = convertEncoderToCM(encoderLine1);
distanceLine2 = convertEncoderToCM(encoderLine2);
distanceLine3 = convertEncoderToCM(encoderLine3);

displayTextLine(1,"line1: %f cm", distanceLine1);
displayTextLine(2,"line2: %f cm", distanceLine2);
displayTextLine(3,"line3: %f cm", distanceLine3);
}
