#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
//*This makes the robot move in each line accurately*//
forward(5.5,rotations, 50);
resetGyro(gyroSensor);
setMotorSpeed(motorC, 50);
setMotorSpeed(motorB, -50);
waitUntil(getGyroDegrees(gyroSensor) < -78.9);
forward(3.2,rotations, 50);
resetGyro(gyroSensor);
setMotorSpeed(motorC, 50);
setMotorSpeed(motorB, -50);
waitUntil(getGyroDegrees(gyroSensor) < -80);
forward(4.9,rotations, 50);
//*The robot is offiacially reacher th middle*//
resetGyro(gyroSensor);
setMotorSpeed(motorC, -50);
setMotorSpeed(motorB, 50);
waitUntil(getGyroDegrees(gyroSensor) > 120);
forward(3.5,rotations, 50);
resetGyro(gyroSensor);
setMotorSpeed(motorC, -50);
setMotorSpeed(motorB, 50);
waitUntil(getGyroDegrees(gyroSensor) > 39);
forward(3.5,rotations, 50);
//*The robot has succefully reach its end!*//
}
