#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
/*ROBOTC will run through obstacles and when the touch sensor detects it will go backward and continue*/
setMotorSpeed(motorC, 50);
setMotorSpeed(motorB, 50);
waitUntil(getTouchValue(touchSensor)==1);
backward(0.2, rotations, 50);
turnLeft(178.8, degrees);
setMotorSpeed(motorC, 50);
setMotorSpeed(motorB, 50);
/*It is now halfway through the challenge*/
waitUntil(getTouchValue(touchSensor)==1);
backward(0.5, rotations, 50);
turnRight(178.9, degrees);
setMotorSpeed(motorC, 50);
setMotorSpeed(motorB, 50);
waitUntil(getTouchValue(touchSensor)==1);
backward(0.1, rotations, 50);
turnRight(165, degrees);
setMotorSpeed(motorC, 50);
setMotorSpeed(motorB, 50);
waitUntil(getTouchValue(touchSensor)==1);
/*Succes it reaches its end*/
}
