#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
/*ROBOTC is going to go face north, east, south abnd west then return*/
task main()
{
setMotorSpeed(motorB, 50);
setMotorSpeed(motorC, 50);
waitUntil(getTouchValue(touchSensor)==1);
backward(3.33, rotations, 30);
turnRight(175, degrees);
setMotorSpeed(motorB, 50);
setMotorSpeed(motorC, 50);
waitUntil(getTouchValue(touchSensor)==1);
backward(3.33,rotations, 40);
turnRight(170, degrees);
setMotorSpeed(motorB, 50);
/*ROBOTC has made it to north and east and returning to go to south and west*/
setMotorSpeed(motorC, 50);
waitUntil(getTouchValue(touchSensor)==1);
backward(3.4, rotations, 49);
turnRight(170, degrees);
setMotorSpeed(motorB, 50);
setMotorSpeed(motorC, 50);
waitUntil(getTouchValue(touchSensor)==1);
backward(3.3, rotations, 48);
}
/*ROBOTC has completed going in many directions and return to its normal position*/
