#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//*In this program it will make the robot go to each color tiles and it will moves as programmed*//
task main()
{
setMultipleMotors(50, motorB, motorC);
waitUntil(getColorName(colorSensor)==colorRed);//*This is for red*//
turnLeft(180,degrees,50);
setMultipleMotors(50, motorB, motorC);
waitUntil(getColorName(colorSensor)==colorBlue);//*This is for blue*//
turnRight(270,degrees,50);
setMultipleMotors(50, motorB, motorC);
waitUntil(getColorName(colorSensor)==colorGreen);//*This is for green*//
stopAllMotors();
}
