#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//*In this program i made the robot run through a maze and also detects black lines*/
task main()
{
setMotor(motorB, 30);
setMotor(motorC, 30);
waitUntil(getColorName(colorSensor) == colorBlack);
  stopAllMotors();
  forward(0.8,rotations,50);
  turnRight(180,degrees,50);
  setMotor(motorB, 30);
setMotor(motorC, 30);
waitUntil(getColorName(colorSensor) == colorBlack);
forward(0.6,rotations,50);
setMotor(motorB, 30);
setMotor(motorC, 30);
waitUntil(getColorName(colorSensor) == colorBlack);
  stopAllMotors();
  forward(0.3,rotations,50);
  setMotor(motorB, 30);
setMotor(motorC, 30);
waitUntil(getColorName(colorSensor) == colorBlack);
  stopAllMotors();
  forward(0.09,rotations,50);
  turnRight(180,degrees,50);
  setMotor(motorB, 30);
setMotor(motorC, 30);
waitUntil(getColorName(colorSensor) == colorBlack);
  stopAllMotors();
/*Around the middle part the robot could have some issue and be mislead but if this happened please re-run about 4-5 times and the robot and it will work*/
  forward(0.4,rotations,50);
  setMotor(motorB, 30);
setMotor(motorC, 30);
waitUntil(getColorName(colorSensor) == colorBlack);
  stopAllMotors();
  forward(1,rotations,50);
  setMotor(motorB, 30);
setMotor(motorC, 30);
waitUntil(getColorName(colorSensor) == colorBlack);
  stopAllMotors();
  forward(0.9,rotations,50);
  turnLeft(180,degrees,50);
   setMotor(motorB, 30);
setMotor(motorC, 30);
waitUntil(getColorName(colorSensor) == colorBlack);
  stopAllMotors();
  forward(0.1,rotations,50);
   setMotor(motorB, 30);
setMotor(motorC, 30);
waitUntil(getColorName(colorSensor) == colorBlack);
  stopAllMotors();
  forward(0.5,rotations,50);
  turnLeft(175,degrees,50);
    setMotor(motorB, 30);
setMotor(motorC, 30);
waitUntil(getColorName(colorSensor) == colorBlack);
  stopAllMotors();
  forward(0.8,rotations,50);
    setMotor(motorB, 30);
setMotor(motorC, 30);
waitUntil(getColorName(colorSensor) == colorBlack);
  stopAllMotors();
  forward(0.4,rotations,50);
    setMotor(motorB, 30);
setMotor(motorC, 30);
waitUntil(getColorName(colorSensor) == colorBlack);
  stopAllMotors();
  forward(0.4,rotations,50);
    setMotor(motorB, 30);
setMotor(motorC, 30);
waitUntil(getColorName(colorSensor) == colorBlack);
  stopAllMotors();
  forward(0.4,rotations,50);
    setMotor(motorB, 30);
setMotor(motorC, 30);
waitUntil(getColorName(colorSensor) == colorBlack);
  stopAllMotors();
  forward(0.4,rotations,50);
    setMotor(motorB, 30);
setMotor(motorC, 30);
waitUntil(getColorName(colorSensor) == colorBlack);
  stopAllMotors();
  forward(0.08,rotations,50);
  turnRight(180,degrees,50);
	forward(2,rotations,50);
	/*The robot has reached the end*/
}
