#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	resetMotorEncoder(motorB);
	resetMotorEncoder(motorB);
	repeatUntil(getMotorEncoder(motorB)> 1460)

{
		if(getColorReflected(colorSensor) < 40)
		{
			setMotorSpeed(leftMotor,10);
			setMotorSpeed(rightMotor,50);
		}
		else
		{
			setMotorSpeed(leftMotor,50);
			setMotorSpeed(rightMotor,10);
		}
	}
}
