#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
task main()
{
		forward(2.0,rotations,50);
		turnLeft(180,degrees);
		forward(3.7,rotations,50);
		turnRight(180,degrees);
		forward(2.0,rotations,50);
		turnRight(180,degrees);
		forward(3.7,rotations,50);
		turnLeft(180,degrees);
		forward(2.0,rotations,50);
		turnLeft(180,degrees);
		forward(5.8,rotations,50);
		turnLeft(180,degrees);
		forward(5.4,rotations,50);
		turnLeft(169,degrees);
		forward(5.0, rotations, 50);
		turnLeft(180,degrees);
		repeat(1)
		{
		/*ROBOTC is now going to repeat the loop*/
		forward(3.4,rotations,50);
		turnLeft(225,degrees);
		forward(3.4,rotations,50);
		turnRight(180,degrees);
		forward(3.0,rotations,50);
		turnRight(190,degrees);
		forward(4.0,rotations,50);
		turnLeft(198,degrees);
		forward(2.0,rotations,50);
		turnLeft(200,degrees);
		forward(5.8,rotations,50);
		turnLeft(215,degrees);
		forward(5.4,rotations,50);
		turnLeft(170,degrees);
		forward(5.0, rotations, 50);
		turnLeft(180,degrees);
}
}
/*ROBOTC has reach the end line*/
