#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int encoderLine1;
task main()
{
resetMotorEncoder(leftMotor);
encoderLine1 =getMotorEncoder(leftMotor);
repeat(5){//*The robot will repeat the code 5 times to make it carries the crate to whichever sides it was programmed to*//
moveMotor(armMotor,1, seconds, -50);
setMultipleMotors(50,motorB,motorC);
waitUntil(getColorName(colorSensor)!=colorWhite);
stopAllMotors();
moveMotor(armMotor,1, seconds, 50);
if(getColorName(colorSensor)== colorGreen)
	{
turnRight(350,degrees,50);//*This sets the dropspot for green*//
setMultipleMotors(50,motorB,motorC);
waitUntil(getUSDistance(sonarSensor)< 15);
turnLeft(365,degrees);
}
else
{
if(getColorName(colorSensor)== colorRed)
	{
turnRight(350,degrees,50);//*This sets the dropspot for green*//
setMultipleMotors(50,motorB,motorC);
waitUntil(getUSDistance(sonarSensor)< 15);
turnLeft(365,degrees);
}
else
{
if(getColorName(colorSensor)== colorBlue)
	{
turnRight(350,degrees,50);//*This sets the dropspot for green*//
setMultipleMotors(50,motorB,motorC);
waitUntil(getUSDistance(sonarSensor)< 15);
turnLeft(365,degrees);
}
}
}
}
}
