#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//*today I will make the robot go through a challenge of obstacles in the program.*//
task main()
{
//*This part will use the touch sensor to dectect if the robot hits the wall and then move on to the linetracking section*//
moveMotor(armMotor,1,seconds,50);
setMotorSpeed(motorB,50);
setMotorSpeed(motorC,50);
waitUntil(getTouchValue(touchSensor)==1);
backward(0.55,rotations,50);
setMotorSpeed(motorB,0);
setMotorSpeed(motorC,0);
turnLeft(175,degrees,50);
forward(1.5,rotations,50);
//*During this part the robot will follow through the ostacles then uses its sonar sensor to detect walls and sometimes there is an error please try again sometimes but 90% of the time it runs perfectly.*//
resetMotorEncoder(motorB);
repeatUntil(getMotorEncoder(motorB)> 1000)

{
	if(getColorReflected(colorSensor) < 40)
        {
            setMotorSpeed(leftMotor,50);
            setMotorSpeed(rightMotor,10);
        }
        else
        {
            setMotorSpeed(leftMotor,10);
            setMotorSpeed(rightMotor,50);
            }
     }
         turnRight(99,degrees,50);
         forward(0.5,rotations,50);
         turnLeft(125,degrees,50);
         resetMotorEncoder(motorC);
repeatUntil(getMotorEncoder(motorC)> 1000)
{
	if(getColorReflected(colorSensor) < 40)
        {
            setMotorSpeed(leftMotor,50);
            setMotorSpeed(rightMotor,10);
        }
        else
        {
            setMotorSpeed(leftMotor,10);
            setMotorSpeed(rightMotor,50);
            }
     }
     turnRight(138,degrees,50);
	   forward(0.09,rotations,50);
	   turnRight(160,degrees,50);
	   setMotorSpeed(motorC, 50);
setMotorSpeed(motorB, 50);
waitUntil(getUSDistance(sonarSensor)< 15);
setMotorSpeed(motorC, 0);
setMotorSpeed(motorB, 0);
//*Right now it will detect red color and turn right and then forward to the finish line*//
		turnRight(178,degrees,50);
		forward(5.4,rotations,50);
		if(getColorName(colorSensor) == colorRed)
	{
		turnRight(180, degrees, 50);
	}
	forward(5,rotations,50);
}
