#pragma config(StandardModel, "RVW Mammalbot")
//!!Code automatically generated by 'ROBOTC' configuration wizard               !!//

task main()
{
forward(9,rotations,50);
//*We're done with first pad/charging point*//
}
