#pragma config(StandardModel, "RVW Mammalbot")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
forward(2,rotations,50);
turnLeft(50,degrees,50);
forward(3,rotations,50);
turnLeft(0,degrees,50);
forward(7,rotations,50);
wait(3,seconds);
forward(7,rotations,50);
turnLeft(150,degrees,50);
forward(7,rotations,50);
//*Here we reached the fourth charging pad*//
}
