#pragma config(StandardModel, "RVW Mammalbot")
//!!Code automatically generated by 'ROBOTC' configuration wizard               !!//

task main()
{
forward(9,rotations,50);
turnRight(140,degrees,50);
forward(5,rotations,50);
turnLeft(159,degrees,50);
forward(7,rotations,50);
//*We're done with second pad charging point*//
}
