#pragma config(StandardModel, "RVW Mammalbot")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
forward(8,rotations,50);
turnLeft(100,degrees,50);
forward(2.5,rotations,50);
turnRight(170,degrees,50);
forward(3,rotations,50);
//*We are now charged at 3rd spot*//
}
