#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int encoderLine1;
int encoderLine2;
int encoderLine3;

float distanceLine1;
float distanceLine2;
float distanceLine3;


void forwardOneLine()
{
    setMultipleMotors(50, motorB, motorC);
    waitUntil(getColorName(colorSensor) == colorBlack);
}

void backwardOneLine()
{
		 setMultipleMotors(-50, motorB, motorC);
    waitUntil(getColorName(colorSensor) == colorBlack);
}
void crossTheLine()
{
    setMultipleMotors(40, motorB, motorC);
    waitUntil(getColorName(colorSensor)!= colorBlack);
}
void backTheLine()
{
	 setMultipleMotors(-40, motorB, motorC);
    waitUntil(getColorName(colorSensor)!= colorBlack);
}
void DontCrossTheLine()
{
    setMultipleMotors(-40, motorB, motorC);
    waitUntil(getColorName(colorSensor)!= colorBlack);
}

float convertEncoderToCM(int encoderCounts)
{
  return (encoderCounts / 360.0)*(PI*5.6);
}
task main()
{
resetMotorEncoder(leftMotor);
forwardOneLine();
crossTheLine();
encoderLine1 = getMotorEncoder(motorB);
forwardOneLine();
crossTheLine();
encoderLine2 = getMotorEncoder(motorB);
setMultipleMotors(50, motorB, motorC);
waitUntil(getUSDistance(sonarSensor)< 15);
setMultipleMotors(-50, motorB, motorC);
encoderLine3 = getMotorEncoder(motorB);
setMultipleMotors(-40, motorB, motorC);
waitUntil(getMotorEncoder(motorB) < 0);

distanceLine1 = convertEncoderToCM(distanceLine1);
distanceLine2 = convertEncoderToCM(distanceLine2);
distanceLine3 = convertEncoderToCM(distanceLine3);

displayTextLine(1,"Pipe1: %f cm", distanceLine1);
displayTextLine(2,"Pipe2: %f cm", distanceLine2);
displayTextLine(3,"Pipe3: %f cm", distanceLine3);
}
