#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//*This program will make robot make its path by color*//
task main()
{
	forward(2.5,rotations, 50);
	//* This path is for red the program will make the robot turn left and forward*//
	if(getColorName(colorSensor) == colorRed)
	{
		turnLeft(180, degrees, 50);
		forward(3.4,rotations,50);
	}
	//*This path is for green the program will make the robot forward to green side*//
					if(getColorName(colorSensor) == colorGreen)
	{
		forward(3.4,rotations,50);
		//*This path is for blue the program will make the robot turn right and forward*//
	}
	if(getColorName(colorSensor) == colorBlue)
	{
		turnRight(180, degrees, 50);
		forward(3.4,rotations,50);
	}
}
