#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
repeat(5){//*The robot will repeat the code 5 times to make it carries the crate to whichever sides it was programmed to*//
moveMotor(armMotor,1, seconds, -50);
setMultipleMotors(50,motorB,motorC);
waitUntil(getColorName(colorSensor)!=colorWhite);
stopAllMotors();
moveMotor(armMotor,1, seconds, 50);
if(getColorName(colorSensor)== colorGreen)
	{
turnLeft(165,degrees,50);//*This sets the dropspot for green*//
setMultipleMotors(50,motorB,motorC);
waitUntil(getColorName(colorSensor) !=colorWhite);
forward(0.5,rotations,50);
stopAllMotors();
moveMotor(armMotor,2,seconds,-40);
backward(1.5,rotations,50);
turnRight(170,degrees,50);
setMultipleMotors(50,motorB,motorC);
moveMotor(armMotor,0.9, seconds, -40);
waitUntil(getColorName(colorSensor) !=colorWhite);
stopAllMotors();
}
else{
if(getColorName(colorSensor)== colorRed)
	{
turnRight(165,degrees,50);//*This sets the dropspot for red*//
setMultipleMotors(50,motorB,motorC);
waitUntil(getColorName(colorSensor) !=colorWhite);
forward(0.5,rotations,50);
stopAllMotors();
moveMotor(armMotor,2,seconds,-40);
backward(1.5,rotations,50);
turnLeft(170,degrees,50);
setMultipleMotors(50,motorB,motorC);
moveMotor(armMotor,0.9, seconds, -40);
waitUntil(getColorName(colorSensor) !=colorWhite);
stopAllMotors();
}
}
}
}
//*Sorry the program wasn't accurate I tried my best*//
