#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
/*Robotc is going to travel and follow the obstacles and repeat 2 times*/
task main()
{
 turnLeft(179, degrees);
 forward(5.5, rotations, 50);
 turnRight(178, degrees);
 forward(5.62, rotations, 50);
 turnRight(176, degrees);
 forward(5.5, rotations, 50);
 turnRight(180, degrees);
 forward(1.6, rotations, 50);
 turnRight(174, degrees);
 forward(3.7, rotations, 50);
 turnLeft(179, degrees);
 forward(2.1, rotations, 50);
 turnLeft(180, degrees);
 forward(3.6, rotations, 50);
 turnRight(179, degrees);
 forward(2.1, rotations, 50);
 turnRight(185, degrees);
 forward(5.62, rotations, 50);
 turnRight(173, degrees);
 forward(5.5, rotations, 50);
 turnRight(179, degrees);
 forward(5.4,rotations, 50);
 turnRight(177, degrees);
 forward(1.8, rotations, 50);
 turnRight(175, degrees);
 forward(3.5, rotations, 50);
 turnLeft(180, degrees);
 forward(1.99, rotations, 50);
 turnLeft(178, degrees);
 forward(3.5, rotations, 50);
 turnRight(180, degrees);
 forward(1.8, rotations, 50);
 turnRight(360, degrees);
 	/*It not has reach the start and will reloop the cycle*/
 forward(1.8,rotations,50);
		turnLeft(180,degrees);
		forward(3.4,rotations,50);
		turnRight(180,degrees);
		forward(1.8,rotations,50);
		turnRight(175,degrees);
		forward(3.5,rotations,50);
		turnLeft(172,degrees);
		forward(1.8,rotations,50);
		turnLeft(180,degrees);
		forward(5.8,rotations,50);
		turnLeft(180,degrees);
		forward(5.4,rotations,50);
		turnLeft(169,degrees);
		forward(5.0, rotations, 50);
		turnLeft(180,degrees);
		repeat(1)
		{
		/*ROBOTC is now going to repeat the loop*/
		forward(3.7,rotations,50);
		turnLeft(225,degrees);
		forward(3.4,rotations,50);
		turnRight(180,degrees);
		forward(3.0,rotations,50);
		turnRight(190,degrees);
		forward(3.0,rotations,50);
		turnLeft(198,degrees);
		forward(2.2,rotations,50);
		turnLeft(200,degrees);
		forward(5.8,rotations,50);
		turnLeft(215,degrees);
		forward(5.4,rotations,50);
		turnLeft(170,degrees);
		forward(5.0, rotations, 50);
		turnLeft(180,degrees);
}
}
