#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//*In this program I made the robot count the lines as it runes through 3 lines*//
int encoderLine1();
int encoderLine2();
int encoderLine3();

void GoOverLine()
{
	resetMotorEncoder(leftMotor);
  setMotor(motorB, 30);
  setMotor(motorC, 30);
  waitUntil(getColorName(colorSensor) != colorBlack);
  stopAllMotors();
}
//* This is for line 1*//
void forwardLine()
{
	resetMotorEncoder(leftMotor);
  setMotor(motorB, 30);
  setMotor(motorC, 30);
  waitUntil(getColorName(colorSensor) != colorWhite);
  stopAllMotors();
}
//* This is for line 2*//
void forwardLine2()
{
	resetMotorEncoder(leftMotor);
  setMotor(motorB, 30);
  setMotor(motorC, 30);
  waitUntil(getColorName(colorSensor) != colorWhite);
  stopAllMotors();
}
//* This iis for line 3*//
void forwardLine3()
{
	resetMotorEncoder(leftMotor);
  setMotor(motorB, 30);
  setMotor(motorC, 30);
  waitUntil(getColorName(colorSensor) != colorWhite);
  stopAllMotors();
}
task main()
{
forwardLine();
GoOverLine();
forwardLine2();
GoOverLine();
forwardLine3();
GoOverLine();
}
