#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//The robot will try to go in yellow area*//
task main()
{
  setMultipleMotors(50, motorB, motorC);
waitUntil(getColorName(colorSensor)!=colorWhite);//*It will go forward and then backwards and then forward to yellow area*//
backward(2,rotations,50);
forward(5,rotations,50);
}
//*Somehow the success bar doesn't show up but my robot follows the instructions*//
