#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int encoderLine1;
//*This program will make the robot go forward to the blackline and keep the encoder counts*//
task main()
{
resetMotorEncoder(leftMotor);

setMotorSpeed(leftMotor, 30);
setMotorSpeed(rightMotor, 30);
//*It will count starting here*//
waitUntil(getColorName(colorSensor) == colorBlack);

setMotorSpeed(leftMotor, 30);
setMotorSpeed(rightMotor, 30;

encoderLine1 = getMotorEncoder(leftMotor);
//*At this point we can check to see our encoder countains at the pipeline*//
}
