#pragma config(StandardModel, "EV3 Trafficbot")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	forward(1.5,rotations,30);
	turnLeft(225,degrees,30);
	forward(5, rotations,40);
if(getColorName(middleColor) == colorRed)
{
sleep(1000);
forward(1,rotations,20);
}
}
