#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	if(getColorName(colorSensor) == colorRed)
	{
		turnLeft(180, degrees, 50);
	}
}
